services:
  maria_db:
    image: mariadb:latest
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD: ecommerce
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data/source.sql:/docker-entrypoint-initdb.d/source.sql:ro
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: maria_db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: ecommerce
    ports:
      - "8081:80"
    depends_on:
      - maria_db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
